### ISSUE TITLE
Problem with new version

### ISSUE THREAD

**Issue by A-Vladimir** [Slava0135/reVision#11]
The latest master version doesn't work at all, and the 8.0 version doesn't have any research instead everything is unlocked.

**Comment by Slava0135** [comment]
> The latest master version doesn't work at all, and the 8.0 version doesn't have any research instead everything is unlocked.

Try reinstalling it. I am not sure about research tree and if I want it at all - thus everything is unlocked.

**Comment by A-Vladimir** [comment]
Too bad, the research tree was good.

**Comment by A-Vladimir** [comment]
would you be willing to share the files for the research tree?
