### ISSUE TITLE
Cant place scrapper on anything but sand

### ISSUE THREAD

**Issue by KarsonTheFoxx** [Slava0135/reVision#18]
According to the input/output placing the scrapper on snow will produce coal, however I'm unable to even place it on anything other than sand, I'm running the game on an s10+ with android 12

**Comment by Slava0135** [comment]
Game version (build)? Tested it on build 135 (PC) and build 126.2 (Android), everything works just fine. Make sure you are running the latest mod version. Also try disabling other mods.

**Comment by KarsonTheFoxx** [comment]
sorry for the late reply, i used the version in the mods tab on the game, i noticed this just seems to be an issue with the game itself because i cannot collect snow period on the android build
