### ISSUE TITLE
Problem with the Android version

### ISSUE THREAD

**Issue by R0cit** [Slava0135/reVision#19]
The mod does not work on the version: alfa 316 (Android)

**Comment by Slava0135** [comment]
There have been breaking changes in modding API in build 136 and I didn't port the mod (yet). Sorry!

**Comment by R0cit** [comment]
Thanks

**Comment by Slava0135** [comment]
> The mod does not work on the version: alfa 316 (Android)

Not sure if you get notification, but I made v7 port (details are in new issue)
