### ISSUE TITLE
mod v7 port - download here!

### ISSUE THREAD

**Issue by Slava0135** [Slava0135/reVision#21]
Until v7 releases I want to keep v6 version in Releases section.
But you can already download v7 version:
> in Actions section - click on most recent workflow (with check mark) - download the artifact!

**Comment by fengjiudianban** [comment]
How to download, I am a first time user of this site

**Comment by Slava0135** [comment]
> How to download, I am a first time user of this site

![Screenshot_20220910-145908_Chrome](https://user-images.githubusercontent.com/40753025/189482311-d05a73c0-dac6-4331-9c0d-03e7e7303ee6.jpg)

Right below, you also would need to unpack it.
